name = "btn2026-modpack"
author = "robotkoer"
version = "0.2.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6803210bf587c651672dc02f042e59c8164ffde0b897f3f0f4dc31b33dbbe1bf"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
