name = "btn2026-modpack"
author = "scotus1"
version = "0.2.0-alpha"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "471142fd7d6eac2c7acede066ce13ca9dbfa94312b3c87ea5b38bf64f979e2aa"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
