name = "Fabulously Optimized"
author = "robotkoer"
version = "12.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a81a02bb79d6c33690542dad176edf52defa54018106e1912febdd0cf34b9f8"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
